baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Sighting Data"
summarylength = 10
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

# Enable Disqus
#disqusShortname = ""
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
title = "Sighting Data"
author = "Tony Lee"
description = "With Tony"
email = "ota.tony.lee@gmail.com"

favicon = "favicons/"
customCss = []

## Social links
[[params.socialIcons]]
icon = "fas fa-linkedin-square"
title = "Linkedin"
url = "https://linkedin.com/in/tony-ta-lee"

## Menu items

[menu]

  [[menu.main]]
  name = "首頁"
  identifier = "home"
  weight = 100
  url = "/"
  
  [[menu.main]]

