baseurl = "/"
languageCode = "en-us"
title = "數據分析與持續改善"
copyright = "&copy; 2018"

enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

[permalinks]
    note = "/note/:year/:month/:day/:slug/"

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "架構介紹"
        url     = "/intro/analysis_frame1"
        weight  = 3
    [[menu.nav]]
        name    = "應用範例"
        url     = "/demo"
        weight  = 5

# Site Params
[params]
    home = "首頁"
    dateFormat = "6 January 2006"
    logo = "images/logo-2.png"
    logo_alt = "logo"
    #logo_text = "logo_text"
    
    # side bar
    featured_tags = true

    # Navigation
    [params.navigation]
        aboutme = "關於"
        cta = "聯絡我"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/home-bg.jpg"
        heading = "數據分析與持續改善"
        subtitle = "運用數據分析及持續改善的架構"
        description = "提升企業的生產力、降低成本、改善品質"
        btn     = true
        
    # Section why and how are built in /partials/why.html

     # Intro Section On Homepage
    [params.intro]
        enable  = true
        #bgImage = "images/white1.jpg"
        title   = "數據分析架構介紹"
        subtitle= "數據分析應用至..."

    # Homepage About Section
    [params.aboutme]
        enable  = true
        image   = "images/about/me.png"

    # Call to Action
    [params.cta]
        enable  = true
        title   = ""
        content = "如果需要了解更多，或者需要問題解決與數據分析的協助，聯絡我。"
        mail = "info@sightingdata.com"
        phone = "0972-268-529"

   
    
